server:
  port: 8088

cas:
  #cas服务端的地址
  server-url-prefix: http://localhost:8080/cas
  #cas服务端的登录地址
  server-login-url: http://localhost:8080/cas/login
  #当前服务器的地址(客户端)
  client-host-url: http://localhost:8088
  #Ticket校验器使用Cas30ProxyReceivingTicketValidationFilter
  validation-type: cas3

casClientLogoutUrl: http://localhost:8080/cas/logout?service=http://localhost:8088/logoutSuccess
